apiVersion: chainsaw.kyverno.io/v1alpha1
kind: Configuration
metadata:
  name: custom-config
spec:
  namespace: kubedatastack
  timeouts:
    apply: 120s
    assert: 360s
    cleanup: 120s
    delete: 120s
    error: 10s
    exec: 45s
  skipDelete: true
  failFast: true
