apiVersion: chainsaw.kyverno.io/v1alpha1
kind: Configuration
metadata:
  name: custom-config
spec:
  timeouts:
    apply: 120s
    assert: 600s
    cleanup: 120s
    delete: 120s
    error: 60s
    exec: 60s
  skipDelete: false
  failFast: true
